#####
## Functions
#####

#' @title Convert habitat suitability raster into presence/absences
#'
#' @description This function converts a habitat suitability raster stack, as generated by `gen_vs_hab_suit`, to presence/absences. The conversion is controlled by the method/parameters specified in the /data/sim_spp/convert_vs_hab_suit_params/convert_vs_hab_suit_params.csv file, which are used by `virtualspecies::convertToPA`.
#'
#' @param vs_hab_suit = A list with the virtual species habitat suitability raster layer (one time step) or stack (multiple time steps) with a species habitat suitability estimated at every grid cell across the spatial domain of interest as governed by the extent and grain of habitat covariate raster layers/stacks. This list is generated by generated by `gen_vs_hab_suit`.
#' @param convert_vs_hab_suit_params = A data frame (one row) with the method/parameter information to use when converting continuous habitat suitability to binary presence/absences.
#'
#' @return A list with converted presence/absence virtual species list `virtualspecies::convertToPA
#'
#' @export

convert_vs_hab_suit <- function(vs_hab_suit, convert_vs_hab_suit_params, seed = 1313) {

  # For debugging
  if (FALSE) {
    # vs_hab_suit <- readRDS(here::here("data/sim_spp/vs_hab_suit_lme/cc_vs_suit.rds"))
    # convert_vs_hab_suit_params<- read.csv(here::here("data/sim_spp/convert_vs_hab_suit_params/convert_vs_hab_suit_params.csv"))

    vs_hab_suit = hab_suit
    convert_vs_hab_suit_params = convert_pa_params_use
    seed = 1313
  }

  set.seed(1272022)

  if ("Sim_Parameters" %in% names(vs_hab_suit)) {
    Sim_Parameters_Ind <- which(names(vs_hab_suit) == "Sim_Parameters")
    vs_hab_suit_use_list <- vs_hab_suit[-Sim_Parameters_Ind]
  } else {
    vs_hab_suit_use_list <- vs_hab_suit
  }

  if (convert_vs_hab_suit_params$PA.method != "custom") {
    # Use `virtualspecies::convertToPA to convert the suitability raster into presence/absences depending on the method/parameters
    # First, need to get just the habitat suitability piece...
    # Lapply virtualspecies::convertToPA function
    if (convert_vs_hab_suit_params$species.prevalence == "NULL") {
      vs_pa_out <- lapply(vs_hab_suit_use_list, FUN = function(x, ...) convertToPA(x, PA.method = convert_vs_hab_suit_params$PA.method, beta = convert_vs_hab_suit_params$beta, alpha = convert_vs_hab_suit_params$alpha, species.prevalence = NULL, plot = FALSE))
    } else {
      vs_pa_out <- lapply(vs_hab_suit_use_list, FUN = function(x, ...) convertToPA(x, PA.method = convert_vs_hab_suit_params$PA.method, beta = convert_vs_hab_suit_params$beta, alpha = convert_vs_hab_suit_params$alpha, species.prevalence = convert_vs_hab_suit_params$species.prevalence, plot = convert_vs_hab_suit_params$plot))
    }
  } else {
    # Use rbinom...
    vs_pa_out <- lapply(vs_hab_suit_use_list, FUN = function(x, ...) calc(x$suitab.raster, fun = function(x) rbinom(prob = x, n = 1, size = 1)))
  }

  # Save and return presence/absence
  return(vs_pa_out)
}

#' @title Main convert habitat suitability raster into presence/absences
#'
#' @description This function loads a habitat suitability raster stack, as generated by `gen_vs_hab_suit`, and then converts it into to presence/absences. The conversion is controlled by the method/parameters specified in the /data/sim_spp/convert_vs_hab_suit_params/convert_vs_hab_suit_params.csv file, which are used by `virtualspecies::convertToPA`.
#'
#' @param vs_hab_suit_path = A path to a list with the virtual species habitat suitability raster layer (one time step) or stack (multiple time steps) with a species habitat suitability estimated at every grid cell across the spatial domain of interest as governed by the extent and grain of habitat covariate raster layers/stacks. This list is generated by generated by `gen_vs_hab_suit`.
#' @param convert_vs_hab_suit_params_path = A file path to a csv file with the method/parameter information to use when converting continuous habitat suitability to binary presence/absences.
#' @param out_file = The path and file name to save the converted presence/absence virtual species list.

#' @return Saves a list with converted presence/absence virtual species list `virtualspecies::convertToPA`
#'
#' @export

main_convert_vs_hab_suit <- function(vs_hab_suit_path, convert_vs_hab_suit_params_path, out_file) {

  # For debugging
  if (FALSE) {
  }

  # Read in habitat suitability list
  vs_hab_suit <- readRDS(vs_hab_suit_path)

  # Read in conversion parameters
  convert_params <- read.csv(convert_vs_hab_suit_params_path)

  # Run conversion function
  vs_pa_out <- convert_vs_hab_suit(vs_hab_suit, convert_params)

  # Save it
  saveRDS(vs_pa_out, file = out_file)
}

#####
## Non-interactive running
#####
if (!interactive()) {
  # Build up our command line argument parser
  p <- arg_parser("Convert habitat suitability raster into presence/absences")
  # Our first argument, the path to the virtual species habitat suitability list, generated by 'gen_vs_hab_suit'
  p <- add_argument(p, "vs_hab_suit_path", help = "A path to a list with the virtual species habitat suitability raster layer (one time step) or stack (multiple time steps) with a species habitat suitability estimated at every grid cell across the spatial domain of interest as governed by the extent and grain of habitat covariate raster layers/stacks. This list is generated by generated by `gen_vs_hab_suit`.")
  # Our second argument, the path to csv file with the method/parameter information to use in the conversion
  p <- add_argument(p, "convert_vs_hab_suit_params_path", help = "A file path to a csv file with the method/parameter information to use when converting continuous habitat suitability to binary presence/absences.")
  # Our third argument, the path and name to save a list with virtual species presence/absence data
  p <- add_argument(p, "out_file", help = "The path and file name to save the converted presence/absence virtual species list.")
  # parse the arguments
  args <- parse_args(p)
  for (i in 1:length(args)) {
    log_info(paste0("Args include ", names(args)[i], ": ", args[[i]]))
  }

  # execute the function
  main_convert_vs_hab_suit(vs_hab_suit_path = args$vs_hab_suit_path, convert_vs_hab_suit_params_path = args$convert_vs_hab_suit_params_path, out_file = args$out_file)

  # update logger
  log_info("Virtual species habitat suitability raster converted to presence/absence and saved")
}