#####
## Functions
#####

#' @title Enhance presence/absence data with covariates
#'
#' @description This function enhances the virtual species presence/absence data with covariate values that will eventually be used in the model fitting process.
#'
#' @param sample_vs_pa_path = The file path for the virtual species sample presence/absence data as generated by `sample_vs_pa.R`
#' @param habitat_covs_dir = The directory for the habitat covariates, with each covariate stored in a separate folder
#' @param out_file = The path and file name to save a dataframe with the enahnced species presence/absence data
#'
#' @return Saves a dataframe with the enhanced species presence/absence data.
#'
#' @export

main_enhance_sample_vs_pa <- function(sample_vs_pa_path, habitat_covs_dir, out_file) {

  # For debugging
  if (FALSE) {
    # sample_vs_pa_path <- here::here("data/sim_spp/vs_hab_suit/ne_vs_samp.rds")
    # habitat_covs_dir <- here::here("data/sim_spp/habitat_covs/")
  }

  # Load in sample_vs_pa data
  sample_vs_pa <- readRDS(sample_vs_pa_path)

  # Only need to keep observations where we actually sampled...
  if ("sample.points" %in% names(sample_vs_pa)) {
    samp_pts <- enframe(lapply(sample_vs_pa, "[[", "sample.points")) %>%
      unnest(value) %>%
      mutate(., "Date" = as.Date(gsub("X", "", gsub("[.]", "-", name)))) %>%
      dplyr::select(., x, y, Date, Real, Observed)
  } else {
    samp_pts <- do.call(rbind, sample_vs_pa) %>%
      mutate(., "Date" = as.Date(gsub("X", "", gsub("[.]", "-", rownames(.))))) %>%
      dplyr::select(., x, y, Date, Real, Observed)
  }


  # Convert to sf object for extraction
  samp_pts_sf <- st_as_sf(samp_pts, coords = c("x", "y"), crs = 4326, remove = FALSE)

  # Now, working through files in the habitat_covs_dir...
  habitat_covs_folds_temp <- list.files(habitat_covs_dir, full.names = TRUE)
  # Don't include the "processed" subfolder
  habitat_covs_folds <- habitat_covs_folds_temp[!grepl("processed", habitat_covs_folds_temp)]
  # Also, just get the covariate names...
  habitat_covs_names <- list.files(habitat_covs_dir, full.names = FALSE)

  # Loop through the habitat covariate subfolders, and then use either the static or dynamic extraction wrapper depending on dimensions of the raster
  for (i in seq_along(habitat_covs_folds)) {
    # Get the raster file...
    rast_file_temp <- list.files(habitat_covs_folds[i], pattern = ".grd", full.names = TRUE)
    rast_stack_temp <- raster::stack(rast_file_temp)

    # Check dimensions
    if (nlayers(rast_stack_temp) == 1) {
      # Static extract
      samp_pts_sf <- static_extract(rast = rast_stack_temp, cov_name = habitat_covs_names[i], sf_points = samp_pts_sf, date_col_name = "Date", df_sf = "sf")
    } else {
      # Dynamic extract
      samp_pts_sf <- dynamic_2d_extract(rast_ts_stack = rast_stack_temp, stack_name = habitat_covs_names[i], t_summ = "daily", t_position = NULL, sf_points = samp_pts_sf, date_col_name = "Date", df_sf = "sf")
    }
  }

  # Save the data frame
  samp_pts_out <- st_drop_geometry(samp_pts_sf)
  saveRDS(samp_pts_out, file = out_file)
}


#####
## Non-interactive running
#####
if (!interactive()) {
  # Build up our command line argument parser
  p <- arg_parser("Enhance presence/absence data with covariates")
  # Our first argument, the path to the virtual species sample presence/absence data as generated by `sample_vs_pa.R`
  p <- add_argument(p, "sample_vs_pa_path", help = "A path to a list with the virtual species presence/absence data.")
  # Our second argument, the directory holding habitat covariate raster layers or stacks
  p <- add_argument(p, "habitat_covs_dir", help = "A directory path to a habitat_covs folder, which has subfolders for each habitat covariate of interest stored as .grd raster layers or raster stacks. ")
  # Our third argument, the path and name to save a list with enahnced sample presence/absence data
  p <- add_argument(p, "out_file", help = "The path and file name to save a dataframe with the enahnced species presence/absence data")
  # parse the arguments
  args <- parse_args(p)
  for (i in 1:length(args)) {
    log_info(paste0("Args include ", names(args)[i], ": ", args[[i]]))
  }

  # execute the function
  main_enhance_sample_vs_pa(sample_vs_pa_path = args$sample_vs_pa_path, habitat_covs_dir = args$habitat_covs_dir, out_file = args$out_file)

  # update logger
  log_info("Virtual species sample presence/absences enhanced and saved.")
}