#####
## Functions
#####

#' @title Sample virtual species presence absences
#'
#' @description This function samples the virtual species presence/absence data to create our full, "truth" data set. The function samples depending on parameters provided by sample_vs_params and uses the virtualSpecies::sampleOccurrences data
#'
#' @param vs_pa = A list with the virtual species presence/absence data.
#' @param region_sf = Either NULL or an sf polygon that will be used to limit the sampling area.
#' @param sample_vs_pa_params = A data frame (one row) with the method/parameter information to use when sampling the virtual species presence/absences
#' @return A list with the sampled presence/absence data
#'
#' @export

sample_vs_pa <- function(vs_pa, region_sf, sample_vs_pa_params) {

  # For debugging
  if (FALSE) {
  }

  cust_sample_function <- function(x) {
    temp_df <- as.data.frame(x, xy = TRUE)
    names(temp_df)[3] <- "Real"
    temp_df$Observed <- temp_df$Real

    # out_df <- temp_df %>%
    #     # sample_n(., size = round((nrow(.) * 0.75), 0)) %>%
    #     drop_na()
    out_df <- temp_df %>%
        # sample_n(., size = round((nrow(.) * 0.75), 0)) %>%
        # drop_na()
    return(out_df)
  }

  # Sampling areas
  vs_sampling.area_use <- as(region_sf, "Spatial")

  if (sample_vs_pa_params$samp_type != "custom") {
    # Sample presence_absence points
    samp_out <- lapply(vs_pa, FUN = function(x, ...) sampleOccurrences(x, n = sample_vs_pa_params$n_samps, type = sample_vs_pa_params$samp_type, sampling.area = sample_vs_pa_params$sampling_area, detection.probability = sample_vs_pa_params$detection_probability, error.probability = sample_vs_pa_params$error_probability, plot = sample_vs_pa_params$plot, sample.prevalence = sample_vs_pa_params$sample_prevalence, replacement = sample_vs_pa_params$replacement))
  } else {
    samp_out <- lapply(vs_pa, FUN = function(x, ...) cust_sample_function(x))
  }


  # Return presence/absence data
  return(samp_out)
}

#' @title Main sampling virtual species presence absence function
#'
#' @description This function loads and samples a virtual species presence/absence list, as generated by `convert_vs_hab_suit`. The sampling is controlled by both the region used and then also the parameters specified in data/sim_spp/sample_vs_pa_params
#'
#' @param vs_pa_path = A path to a list with the virtual species presence/absence data.
#' @param region_sf_path = Either NULL or the file path to an sf polygon that will be used to limit the sampling area.
#' @param sample_vs_pa_params_path = A file path that to the sample parameters file that will be used in virtualSpecies::sampleOcurrences
#' @param out_file = The path and file name to save the sampled species presence/absence data. This is the full "true" dataset.

#' @return Saves a list with sampled presence/absences.
#'
#' @export

main_sample_vs_pa <- function(vs_pa_path, region_sf_path, sample_vs_pa_params_path, out_file) {

  # For debugging
  if (FALSE) {
  }

  # Read in the presence absence list
  vs_pa <- readRDS(vs_pa_path)

  # Read in the region_sf
  if (!is.null(region_sf_path)) {
    region_sf <- st_read(region_sf_path)
  }

  # Read in sampling parameters
  sample_params <- read.csv(sample_vs_pa_params_path)

  # Run sampling function
  samp_out <- sample_vs_pa(vs_pa = vs_pa, region_sf = region_sf, sample_vs_pa_params = sample_params)

  # Save it
  saveRDS(samp_out, file = out_file)
}

#####
## Non-interactive running
#####
if (!interactive()) {
  # Build up our command line argument parser
  p <- arg_parser("Sample virtual species presence/absence data")
  # Our first argument, the path to the virtual species presence/absence list, generated by 'convert_vs_hab_suit'
  p <- add_argument(p, "vs_pa_path", help = "A path to a list with the virtual species presence/absence data.")
  # Our second argument, the path to sf file to set spatial extent for the sampling
  p <- add_argument(p, "region_sf_path", help = "Either NULL or the file path to an sf polygon that will be used to limit the sampling area.")
  # Our third arugment, the path to a csv file with the sampling parameters, which get used by virtualSpecies::sampleOcurrences.
  p <- add_argument(p, "sample_vs_pa_params_path", help = "A file path that to the sample parameters file that will be used in virtualSpecies::sampleOcurrences.")
  # Our fourth argument, the path and name to save a list with sample presence/absence data
  p <- add_argument(p, "out_file", help = "The path and file name to save the sampled species presence/absence data. This is the full 'true' dataset.")
  # parse the arguments
  args <- parse_args(p)
  for (i in 1:length(args)) {
    log_info(paste0("Args include ", names(args)[i], ": ", args[[i]]))
  }

  # execute the function
  main_sample_vs_pa(vs_pa_path = args$vs_pa_path, region_sf_path = args$region_sf_path, sample_vs_pa_params_path = args$sample_vs_pa_params_path, out_file = args$out_file)

  # update logger
  log_info("Virtual species presence/absences sampled and saved.")
}